config/routes.rb
TransfairTest::Application.routes.draw do
  resources :ratings

  resources :jobs

  resources :employments

  resources :service_partners

	match '/' => 'application#test'

end

app/models/employment.rb
class Employment < ActiveRecord::Base
  attr_accessible :job, :rating_servicepartner, :service_partner_id, :job_id
	belongs_to :service_partner
	belongs_to :job
end

app/controllers/employments_controller.rb
class EmploymentsController < ApplicationController
  # GET /employments
  # GET /employments.json
  def index
    @employments = Employment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @employments }
    end
  end

  # GET /employments/1
  # GET /employments/1.json
  def show
    @employment = Employment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employment }
    end
  end

  # GET /employments/new
  # GET /employments/new.json
  def new
    @employment = Employment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employment }
    end
  end

  # GET /employments/1/edit
  def edit
    @employment = Employment.find(params[:id])
  end

  # POST /employments
  # POST /employments.json
  def create
    @employment = Employment.new(params[:employment])

    respond_to do |format|
      if @employment.save
        format.html { redirect_to @employment, notice: 'Employment was successfully created.' }
        format.json { render json: @employment, status: :created, location: @employment }
      else
        format.html { render action: "new" }
        format.json { render json: @employment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employments/1
  # PUT /employments/1.json
  def update
    @employment = Employment.find(params[:id])

    respond_to do |format|
      if @employment.update_attributes(params[:employment])
        format.html { redirect_to @employment, notice: 'Employment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @employment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employments/1
  # DELETE /employments/1.json
  def destroy
    @employment = Employment.find(params[:id])
    @employment.destroy

    respond_to do |format|
      format.html { redirect_to employments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/employments_helper.rb
module EmploymentsHelper
end

app/views/employments/_form.html.erb
<%= form_for(@employment) do |f| %>
  <% if @employment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employment.errors.count, "error") %> prohibited this employment from being saved:</h2>

      <ul>
      <% @employment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rating_servicepartner %><br />
    <%= f.number_field :rating_servicepartner %>
  </div>
  <div class="field">
    <%= f.label :job %><br />
    <%= f.number_field :job %>
  </div>
  <div class="field">
    <%= f.label :service_partner_id %><br />
    <%= f.number_field :service_partner_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employments/edit.html.erb
<h1>Editing employment</h1>

<%= render 'form' %>

<%= link_to 'Show', @employment %> |
<%= link_to 'Back', employments_path %>

app/views/employments/index.html.erb
<h1>Listing employments</h1>

<table>
  <tr>
    <th>Rating servicepartner</th>
    <th>Job</th>
    <th>Service partner</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @employments.each do |employment| %>
  <tr>
    <td><%= employment.rating_servicepartner %></td>
    <td><%= employment.job %></td>
    <td><%= employment.service_partner_id %></td>
    <td><%= link_to 'Show', employment %></td>
    <td><%= link_to 'Edit', edit_employment_path(employment) %></td>
    <td><%= link_to 'Destroy', employment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Employment', new_employment_path %>

app/views/employments/new.html.erb
<h1>New employment</h1>

<%= render 'form' %>

<%= link_to 'Back', employments_path %>

app/views/employments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Rating servicepartner:</b>
  <%= @employment.rating_servicepartner %>
</p>

<p>
  <b>Job:</b>
  <%= @employment.job %>
</p>

<p>
  <b>Service partner:</b>
  <%= @employment.service_partner_id %>
</p>


<%= link_to 'Edit', edit_employment_path(@employment) %> |
<%= link_to 'Back', employments_path %>