config/routes.rb
TransfairTest::Application.routes.draw do
  resources :ratings

  resources :jobs

  resources :employments

  resources :service_partners

	match '/' => 'application#test'

end

app/models/service_partner.rb
class ServicePartner < ActiveRecord::Base
	has_many :employments
end

app/controllers/service_partners_controller.rb
class ServicePartnersController < ApplicationController
  # GET /service_partners
  # GET /service_partners.json
  def index
    @service_partners = ServicePartner.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @service_partners }
    end
  end

  # GET /service_partners/1
  # GET /service_partners/1.json
  def show
    @service_partner = ServicePartner.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @service_partner }
    end
  end

  # GET /service_partners/new
  # GET /service_partners/new.json
  def new
    @service_partner = ServicePartner.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @service_partner }
    end
  end

  # GET /service_partners/1/edit
  def edit
    @service_partner = ServicePartner.find(params[:id])
  end

  # POST /service_partners
  # POST /service_partners.json
  def create
    @service_partner = ServicePartner.new(params[:service_partner])

    respond_to do |format|
      if @service_partner.save
        format.html { redirect_to @service_partner, notice: 'Service partner was successfully created.' }
        format.json { render json: @service_partner, status: :created, location: @service_partner }
      else
        format.html { render action: "new" }
        format.json { render json: @service_partner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /service_partners/1
  # PUT /service_partners/1.json
  def update
    @service_partner = ServicePartner.find(params[:id])

    respond_to do |format|
      if @service_partner.update_attributes(params[:service_partner])
        format.html { redirect_to @service_partner, notice: 'Service partner was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @service_partner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_partners/1
  # DELETE /service_partners/1.json
  def destroy
    @service_partner = ServicePartner.find(params[:id])
    @service_partner.destroy

    respond_to do |format|
      format.html { redirect_to service_partners_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/service_partners_helper.rb
module ServicePartnersHelper
end

app/views/service_partners/_form.html.erb
<%= form_for(@service_partner) do |f| %>
  <% if @service_partner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service_partner.errors.count, "error") %> prohibited this service_partner from being saved:</h2>

      <ul>
      <% @service_partner.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/service_partners/edit.html.erb
<h1>Editing service_partner</h1>

<%= render 'form' %>

<%= link_to 'Show', @service_partner %> |
<%= link_to 'Back', service_partners_path %>

app/views/service_partners/index.html.erb
<h1>Listing service_partners</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @service_partners.each do |service_partner| %>
  <tr>
    <td><%= link_to 'Show', service_partner %></td>
    <td><%= link_to 'Edit', edit_service_partner_path(service_partner) %></td>
    <td><%= link_to 'Destroy', service_partner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Service partner', new_service_partner_path %>

app/views/service_partners/new.html.erb
<h1>New service_partner</h1>

<%= render 'form' %>

<%= link_to 'Back', service_partners_path %>

app/views/service_partners/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_service_partner_path(@service_partner) %> |
<%= link_to 'Back', service_partners_path %>